version: '3.8'

services:
  elasticsearch:
    image: docker.elasticsearch.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - 9200:9200
    environment:
      - discovery.type: single-node
  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  eureka:
    image: sfgbeerworks/sfg-brewery-eureka
    ports:
      - 8761:8761
  config:
    image: filipecanatto/mssc-config-server
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
  inventory-service:
    image: filipecanatto/mssc-beer-inventory-service
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - config
      - jms
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.15.31:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://MyUserName:MySecretPassword@config:8888"}}}}'
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
  inventory-failover:
    image: sfgbeerworks/sfg-brewery-inventory-failover
    depends_on:
      - eureka
      - config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADRESS: 'true'
  beer-service:
    image: filipecanatto/mssc-beer-service
    ports:
      - 8080:8080
    depends_on:
      - eureka
      - config
      - jms
      - inventory-failover
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.15.31:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://MyUserName:MySecretPassword@config:8888"}}}}'
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
  order-service:
    image: filipecanatto/mssc-beer-order-service
    ports:
      - 8081:8081
    depends_on:
      - eureka
      - config
      - jms
      - beer-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.15.31:3306/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://MyUserName:MySecretPassword@config:8888"}}}}'
      SFG_BREWERY_BEER_SERVICE_HOST: http://beer-service:8080
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
  gateway:
    image: filipecanatto/mssc-brewery-gateway
    ports:
      - 9090:9090
    depends_on:
      - eureka
      - config
      - inventory-service
      - inventory-failover
      - beer-service
      - order-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure



